# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='matching',
            field=models.ManyToManyField(to='finder.Site'),
        ),
        migrations.AddField(
            model_name='matches',
            name='tags',
            field=models.ManyToManyField(to='finder.Tag'),
        ),
    ]
